apiVersion : apps/v1
kind: Deployment
metadata:
  name: helloworldservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldservice
  template:
    metadata:
      labels:
        app: helloworldservice 
    spec:
      containers:
        - name: helloworldservice 
          image: helloworldservicecontainer.azurecr.io/helloworldservice
          ports:
          - containerPort: 8080