# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Hello world'
          ls -l
          echo "foo is: $(FOO)"
          echo "bar is: $(BAR)"
           
    - task: Bash@3
      name: 'just_echoing'
      inputs:
        targetType: 'inline'
        script: |
          echo 'STILL HERE'
          
    - task: Bash@3
      name: 'install_software'
      inputs:
        filePath: 'cdktf-azure-devops-experiment/pipeline-scripts/install-software.sh'
    
    - upload: manifests
      artifact: manifests
