apiVersion : apps/v1
kind: Deployment
metadata:
  name: helloservice-deployment
  labels:
    app: helloservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      containers:
        - name: helloservice
          image: azurecelldemodeveloperchris.azurecr.io/helloservice:latest
          ports:
          - containerPort: 8080
