trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /application/Core/**
resources:
- repo: self
stages:
- stage: BuildStage
  displayName: Build
  dependsOn: 
  jobs:
  - job: BuildStage
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "This step would typically call 'make', but any build steps could go here."
          ls -l
- stage: ReleaseStage
  displayName: Release
  dependsOn: BuildStage
  jobs:
  - job: ReleaseStage
    displayName: Release
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "This project has no release artifacts; no-op."
          ls -l
- stage: CellDeployWave1
  displayName: Deploy (Wave 1)
  dependsOn: ReleaseStage
  jobs:
  - job: CellDeployalpha
    displayName: alpha
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "(alpha) Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
- stage: CellDeployWave2
  displayName: Deploy (Wave 2)
  dependsOn: ReleaseStage
  jobs:
  - job: CellDeploywestus3-1
    displayName: westus3-1
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "(westus3-1) Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
  - job: CellDeploysouthcentralus-1
    displayName: southcentralus-1
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "(southcentralus-1) Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
- stage: CellDeployWave3
  displayName: Deploy (Wave 3)
  dependsOn: ReleaseStage
  jobs:
  - job: CellDeploywestus2-1
    displayName: westus2-1
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "(westus2-1) Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
  - job: CellDeployeastus1-1
    displayName: eastus1-1
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "(eastus1-1) Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
