trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /application/HelloService/**
resources:
- repo: self
stages:
- stage: BuildStage
  displayName: Build
  dependsOn: 
  jobs:
  - job: BuildStage
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "This step would typically call 'make', but any build steps could go here."
          ls -l
- stage: ReleaseStage
  displayName: Release
  dependsOn: BuildStage
  jobs:
  - job: ReleaseStage
    displayName: Release
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "Here we would run commands to build and push a docker image to ACR; e.g. `docker build`, `acr login`, `docker push`."
          ls -l
- stage: CellDeployStage1
  displayName: cdktf deploy
  dependsOn: ReleaseStage
  jobs:
  - job: CellDeployStage1
    displayName: cdktf deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |2

          echo "Here we would run commands to deploy infrastructure via CDK for TerraForm."
          ls -l
