trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /application/TimeService/**
resources:
- repo: self
stages:
- stage: Build
  displayName: Build
  dependsOn: 
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - # A Description
      hello: |2

        echo "Any build steps could go here."
        ls -l
      task: CmdLine@2
- stage: Release
  displayName: Release
  dependsOn: Build
  jobs:
  - job: Release
    displayName: Release
    pool:
      vmImage: ubuntu-latest
    steps:
    - # A Description
      hello: |2

        echo "Any build steps could go here."
        ls -l
      task: CmdLine@2
